name: Lint

concurrency:
  group: lint-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on: pull_request

permissions:
  actions: read
  checks: write
  contents: read
  pull-requests: read

jobs:
  trunk-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Trunk Check
        uses: trunk-io/trunk-action@86b68ffae610a05105e90b1f52ad8c549ef482c2

  conventional-title:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
